version: '3'

services: 
    mysql:
        container_name: mysql
        build:
        context: .
        dockerfile: Dockerfile
        environment:
        - admin
        volumes:
        - /private/data/mysql:/var/lib/mysql
        - ./.temp:/.temp
        ports:
        - "3306:3306"
    backend: 
        build:
            context: .
            dockerfile: docker/Dockerfile.backend.dockerfile
        image: semester/backend
        container_name: semesterBackend
        ports:
            - 8080:8080
        links:
            - mysql
    # frontend: 
    #     build:
    #         context: .
    #         dockerfile: docker/Dockerfile.frontend.dockerfile
    #     image: semester/frontend
    #     container_name: semesterFrontend
    #     ports:
    #         - 3000:3000