version: '3'

services: 
    backend: 
        build:
            context: .
            dockerfile: docker/Dockerfile.backend
        image: backend
        container_name: backend
        volumes:
            - ./backend/target:/app
        ports:
            - ${BACKEND_PORT}
        networks: 
                - semester-organizer-network
    frontend: 
        build:
            context: .
            dockerfile: docker/Dockerfile.frontend
        image: frontend
        container_name: frontend
        ports:
            - ${FRONTEND_PORT}
        networks: 
                - semester-organizer-network
    mongodb:
        image: mongo:latest # use the latest image.
        container_name: mongodb
        restart: unless-stopped
        environment: # set required env variables to access mongo
            - MONGO_USERNAME=${MONGO_USERNAME}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
        ports:
            - ${MONGODB_PORT}
        volumes: # optional to preserve database after container is deleted.
            - ./database-data:/data/db
networks:    
    semester-organizer-network:
        driver: bridge            